### ISSUE TITLE
Rust Application Demo not launching (due to winit error)

### ISSUE THREAD

**Issue by GalacticalEdge** [pop-os/libcosmic#445]
`2024-05-14T23:09:02.104691Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
thread 'main' panicked at /home/user/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/3cfc5c1/iced/tiny_skia/src/window/compositor.rs:56:10:
Create softbuffer surface for window: PlatformError(Some("Visual 0x88 does not use softbuffer's pixel format and is unsupported"), None)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

I am not sure what to do here, but has anyone run into this kind of issue? If so, could anyone give me advice. Thanks!

**Comment by wiiznokes** [comment]
Yes, I think it's a bug in softbuffer. It is only present on x11

**Comment by GalacticalEdge** [comment]
> Yes, I think it's a bug in softbuffer. It is only present on x11

Do you know if this is being worked on?

**Comment by wiiznokes** [comment]
https://github.com/rust-windowing/softbuffer/issues/215

**Comment by psychon** [comment]
Winit issue about incorrect usage of softbuffer (even though nothing in the bug explicitly says so): https://github.com/rust-windowing/winit/issues/3646

Another winit issue about the same problem: https://github.com/rust-windowing/winit/issues/3701

**Comment by zinifier** [comment]
This has been fixed in softbuffer upstream. Need libcosmic to update to a later softbuffer. I opened this PR which fixes the problem for me: https://github.com/pop-os/softbuffer/pull/1

**Comment by vvzen** [comment]
I ran into the same issue on my PopOS system when testing out the [examples/menu](https://github.com/pop-os/libcosmic/blob/92ec78ba29fa32d38287323001c4d6f736680950/examples/menu/src/main.rs) :

```rust
$ RUST_BACKTRACE=1 cargo run 
[...]
2025-08-02T18:16:34.425992Z  INFO winit::platform_impl::linux::x11::window: Guessed window scale factor: 1

thread 'main' panicked at [redacted]/libcosmic/iced/tiny_skia/src/window/compositor.rs:68:10:
Create softbuffer surface for window: PlatformError(Some("Visual 0x82 does not use softbuffer's pixel format and is unsupported"), None)
stack backtrace:
2025-08-02T18:16:34.431385Z ERROR cosmic::theme::portal: Failed to get the contrast Portal(NotFound("Requested setting not found"))
   0: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/result.rs:1732:5
   3: core::result::Result<T,E>::expect
             at /home/vv/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1089:23
   4: <iced_tiny_skia::window::compositor::Compositor as iced_graphics::compositor::Compositor>::create_surface
             at [redacted]/libcosmic/iced/tiny_skia/src/window/compositor.rs:64:22
   5: iced_winit::program::window_manager::WindowManager<P,C>::insert
             at [redacted]/libcosmic/iced/winit/src/program/window_manager.rs:48:23
   6: iced_winit::program::run_instance::{{closure}}
             at [redacted]/libcosmic/iced/winit/src/program.rs:1074:30
   7: iced_winit::program::run::Runner<Message,F,C>::process_event
             at [redacted]/libcosmic/iced/winit/src/program.rs:484:28
   8: iced_winit::program::run::Runner<Message,F,C>::process_event
             at [redacted]/libcosmic/iced/winit/src/program.rs:594:33
   9: <iced_winit::program::run::Runner<Message,F,C> as winit::application::ApplicationHandler>::window_event
             at [redacted]/libcosmic/iced/winit/src/program.rs:355:13
  10: <&mut A as winit::application::ApplicationHandler>::window_event
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/application.rs:359:9
  11: <&mut A as winit::application::ApplicationHandler>::window_event
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/application.rs:359:9
  12: winit::platform_impl::linux::x11::EventLoop::drain_events::{{closure}}
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/platform_impl/linux/x11/mod.rs:586:29
  13: winit::platform_impl::linux::x11::event_processor::EventProcessor::process_event
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/platform_impl/linux/x11/event_processor.rs:122:13
  14: winit::platform_impl::linux::x11::EventLoop::drain_events
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/platform_impl/linux/x11/mod.rs:576:13
  15: winit::platform_impl::linux::x11::EventLoop::single_iteration
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/platform_impl/linux/x11/mod.rs:520:9
  16: winit::platform_impl::linux::x11::EventLoop::pump_app_events
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/platform_impl/linux/x11/mod.rs:420:13
  17: winit::platform_impl::linux::x11::EventLoop::run_app_on_demand
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/platform_impl/linux/x11/mod.rs:385:19
  18: winit::platform_impl::linux::x11::EventLoop::run_app
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/platform_impl/linux/x11/mod.rs:376:9
  19: winit::platform_impl::linux::EventLoop::run_app
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/platform_impl/linux/mod.rs:427:56
  20: winit::event_loop::EventLoop::run_app
             at /home/vv/.cargo/git/checkouts/winit-d03127a0b2faf55d/1cc02bd/src/event_loop.rs:228:9
  21: iced_winit::program::run
             at [redacted]/libcosmic/iced/winit/src/program.rs:687:17
  22: iced::program::Program::run_with
             at [redacted]/libcosmic/iced/src/program.rs:183:12
  23: cosmic::app::multi_window::MultiWindow<P>::run_with
             at [redacted]/libcosmic/src/app/multi_window.rs:126:9
  24: cosmic::app::run
             at [redacted]/libcosmic/src/app/mod.rs:133:9
  25: menu::main
             at ./src/main.rs:36:5
  26: core::ops::function::FnOnce::call_once
             at /home/vv/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
```
