### ISSUE TITLE
Application example panics on Windows when using tinyskia

### ISSUE THREAD

**Issue by netraptor** [pop-os/libcosmic#741]
When running the `application` example on Windows 11 with the `wgpu` feature turned off, the app crashes and panics usually after a few seconds of interacting with the UI.

Steps to reproduce (on a Windows 11 machine/VM):
1. Clone the libcosmic repo and initialize the iced submodule
2. In the Cargo.toml for the `application` example, comment out the following features: xdg-portal, dbus-config, a11y, wayland, wgpu
3. Run the `application` example
4. When the window loads, interact with the window in various ways; the app should crash after a few moments

Crash output (with RUST_BACKTRACE set):
```
thread 'main' panicked at core\src\slice\sort\shared\smallsort.rs:860:5:
user-provided comparison function does not correctly implement a total order
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
   2: core::slice::sort::shared::smallsort::panic_on_ord_violation
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\slice\sort\shared\smallsort.rs:860
   3: core::slice::sort::shared::smallsort::insert_tail
   4: core::slice::sort::stable::quicksort::quicksort
   5: core::slice::sort::stable::drift::sort
   6: core::iter::adapters::try_process
   7: iced_graphics::damage::group
   8: <iced_tiny_skia::window::compositor::Compositor as iced_graphics::compositor::Compositor>::present
   9: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold
  10: iced_winit::program::run::Runner<Message,F,C>::process_event
  11: winit::platform_impl::windows::event_loop::EventLoop::run_app_on_demand::{{closure}}
  12: winit::platform_impl::windows::event_loop::runner::EventLoopRunner::loop_destroyed
  13: winit::platform_impl::windows::event_loop::runner::EventLoopRunner::send_event
  14: winit::platform_impl::windows::event_loop::public_window_callback_inner::{{closure}}
  15: winit::platform_impl::windows::event_loop::runner::EventLoopRunner::catch_unwind
  16: winit::platform_impl::windows::event_loop::public_window_callback
  17: CallWindowProcW
  18: SendMessageW
  19: GetWindowDpiAwarenessContext
  20: KiUserCallbackDispatcher
  21: NtUserDispatchMessage
  22: IsWindowUnicode
  23: winit::platform_impl::windows::event_loop::EventLoop::wait_and_dispatch_message
  24: iced_winit::program::run
  25: cosmic::app::run
  26: application::App::update_title
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\Users\XXXXXXX\projects\libcosmic\target\release\application.exe` (exit code: 101)
```

**Comment by wiiznokes** [comment]
Should be fixed in the next iced rebase

**Comment by netraptor** [comment]
Fixed with the latest iced update.
